# https://taskfile.dev

version: '3'

silent: true

tasks:
  default:
    cmds:
      - task --list

  start-backend:
    desc: Start the backend
    dir: backend
    cmds:
      - ./gradlew :backend:run

  start:
    desc: Start backend, frontend and DB
    dir: backend
    cmds:
      - docker-compose up -d

  stop:
    desc: Stop backend, frontend and DB
    dir: backend
    cmds:
      - docker-compose down

  build-backend:
    desc: Builds the backend and generates a new docker image
    dir: backend
    cmds:
      - ./gradlew :backend:buildDockerImage

  test-backend:
    desc: Builds the backend and runs the tests
    cmds:
      - ./gradlew :backend:test