# https://taskfile.dev

version: '3'

silent: true

tasks:
  default:
    cmds:
      - task --list

  start-backend:
    desc: Start the backend locally with gradle
    cmds:
      - ./gradlew :backend:bootRun

  start-frontend:
    desc: Start the frontend locally with yarn

  start:
    desc: Start backend, frontend and DB using docker containers
    dir: backend
    cmds:
      - docker-compose up -d

  stop:
    desc: Stop backend, frontend and DB
    dir: backend
    cmds:
      - docker-compose down

  build-backend-image:
    desc: Builds the backend and generates a new docker image
    cmds:
      - ./gradlew :backend:buildDockerImage

  push-backend-image:
    desc: Uploads the backend image to dockerhub
    cmds:
      - ./gradlew :backend:pushDockerImage

  build-frontend:
    desc: Builds the frontend and generates a new docker image
    dir: frontend
    cmds:
      - yarn run docker:build

  test-backend:
    desc: Builds the backend and runs the tests
    cmds:
      - ./gradlew :backend:test

  test-frontend:
    desc: Runs all yarn tests for the frontend
    dir: frontend
    cmds:
      - yarn test

  start-DB:
    desc: Starts the MYSQL database
    dir: backend
    cmds:
      - docker-compose run -d --name mysql --service-ports db

  stop-DB:
    desc: Stops the MYSQL database
    dir: backend
    cmds:
      - docker stop mysql
      - docker rm mysql