version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Nak4pic.mysql"
      MYSQL_DATABASE: jocks-karaoke
    volumes:
      - db-data:/var/lib/sql
  backend:
    image: aldoink/jocks-karaoke:backend_1.0.0
    container_name: backend
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#    depends_on:
#      - db
  frontend:
    image: aldoink/jocks-karaoke:frontend_2.0.0
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db-data:
    driver: local