version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: jocks-karaoke
    volumes:
      - db-data:/var/lib/sql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  backend:
    image: aldoink/jocks-karaoke:backend_1.0.0
    container_name: backend
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on:
      - db
  frontend:
    image: aldoink/jocks-karaoke:frontend_1.0.0
    container_name: frontend
    restart: always
    network_mode: host
    depends_on:
      - backend

volumes:
  db-data:
    driver: local