INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0270", "Yazoo", "Only You");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0272", "Fergal Sharkey", "A Good Heart");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0273", "Cure", "Love Cats");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0274", "Snow Patrol ", "Run");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0275", "Boney M", "Rivers of Babylon");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0276", "OMD", "Enola Gay");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0277", "Eurythmics & Aretha Franklin", "Sisters Are Doin' It For Themselves");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0278", "Bryan Adams", "Heaven");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0279", "Love Affair", "Everlasting Love");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0280", "Bad Manners", "Lip Up Fatty");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0281", "Bad Manners", "Special Brew");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0282", "Wings", "Mull of Kintyre");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0283", "Kid Rock", "All Summer Long");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0284", "Fat Larry's Band", "Zoom");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0285", "James", "Laid");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("WP-0286", "Razorlight", "Golden Touch");