DELETE FROM SONGS WHERE LOCATION = "WP-0323";
DELETE FROM SONGS WHERE LOCATION = "WP-0324";
DELETE FROM SONGS WHERE LOCATION = "WP-0325";
DELETE FROM SONGS WHERE LOCATION = "WP-0326";
DELETE FROM SONGS WHERE LOCATION = "WP-0327";
DELETE FROM SONGS WHERE LOCATION = "WP-0328";
DELETE FROM SONGS WHERE LOCATION = "WP-0329";
DELETE FROM SONGS WHERE LOCATION = "WP-0330";

INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0323", "Sister Sledge", "Frankie");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0324", "Jim Diamond", "I Should Have Known Better");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0325", "Jim Diamond", "Hi Ho Silver");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0326", "Paul McCartney and Wings", "Band on the Run");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0327", "Source feat Candi Staton", "You Got The Love");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0328", "Joni Mitchell", "Both Sides Now");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0329", "Spice Girls", "Mama");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0330", "Noah Kahan", "Stick Season");