DELETE FROM SONGS WHERE LOCATION = "WP-0317";
DELETE FROM SONGS WHERE LOCATION = "WP-0318";
DELETE FROM SONGS WHERE LOCATION = "WP-0319";
DELETE FROM SONGS WHERE LOCATION = "WP-0320";
DELETE FROM SONGS WHERE LOCATION = "WP-0321";
DELETE FROM SONGS WHERE LOCATION = "WP-0322";

INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0317", "Oasis", "Stand By Me");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0318", "Talking Heads", "Road to Nowhere");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0319", "Cure", "Just Like Heaven");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0320", "Deep Blue Something", "Breakfast at Tiffany's");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0321", "REM", "Shiny Happy People");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("WP-0322", "REM", "The One I Love");