INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0676", "The Corrs", "So Young");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0677", "The Corrs", "Breathless");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0678", "B*Witched", "C'est La Vie");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0679", "LeAnn Rimes", "Can't Fight The Moonlight");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0680", "Boomtown Rats", "I Don't Like Mondays");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0681", "Jeff Beck", "Hi Ho Silver Lining");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0682", "Waterboys", "Fisherman's Blues");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0683", "Deacon Blue", "Real Gone Kid");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0684", "Lou Reed", "Walk On The Wild Side");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0685", "Stranglers", "Golden Brown");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0686", "Echo And The Bunnymen", "Nothing Lasts Forever");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0687", "Blondie", "Sunday Girl");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0688", "Mumford And Sons", "I Will Wait");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0689", "Andra Day", "Rise Up");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0690", "Candi Staton", "Young Hearts Run Free");