CREATE TABLE IF NOT EXISTS USERS
(
    ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL    VARCHAR(50)  NULL UNIQUE,
    USERNAME VARCHAR(20)  NULL UNIQUE,
    PASSWORD VARCHAR(120) NULL
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID   INT(11)     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID BIGINT(20) NOT NULL,
    ROLE_ID INT(11)    NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

INSERT INTO ROLES(NAME)
VALUES ('ROLE_USER');
INSERT INTO ROLES(NAME)
VALUES ('ROLE_ADMIN');