CREATE TABLE IF NOT EXISTS HIGH_SCORE
(
    ID      INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(50) NOT NULL,
    SCORE   INT         NOT NULL,
    SONG_ID INT         NOT NULL,
    FOREIGN KEY (SONG_ID) REFERENCES SONGS (ID)
);