INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0691","Kate Bush","Hounds of Love");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0692","Laura Branigan","Gloria");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0693","The Corrs","Runaway");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0694","Yazoo","Only You");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0695","Bing Crosby & David Bowie","Peace On Earth / Little Drummer Boy");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0696","Saint PHNX","Happy Place");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0697","The Kinks","Sunny Afternoon");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0698","Electric Light Orchestra","Mr Blue Sky");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0699","Talking Heads","Burning Down The House");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0700","Fern Kinney","Together We Are Beautiful");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0701","Danny Wilson","Mary's Prayer");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0702","Newton Faulkner","Dream Catch Me");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0703","Roger Miller","King Of The Road");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0704","Emeli Sande","Next To Me");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE) VALUES ("GP-0705","Frankie Miller","Darlin'");

UPDATE SONGS SET TITLE="Story Of My Life" WHERE LOCATION="BP-0112";
UPDATE SONGS SET ARTIST="Harry Styles" WHERE LOCATION="GP-0546";

UPDATE SONGS SET ARTIST = "Alan Jackson & Jimmy Buffett", TITLE = "It's Five O'Clock Somewhere" WHERE LOCATION = "RP-0501";
UPDATE SONGS SET ARTIST = "Brad Paisley", TITLE = "Alcohol" WHERE LOCATION = "RP-0502";
UPDATE SONGS SET ARTIST = "Gretchen Wilson", TITLE = "Here For The Party" WHERE LOCATION = "RP-0503";
UPDATE SONGS SET ARTIST = "Gretchen Wilson", TITLE = "Redneck Woman" WHERE LOCATION = "RP-0504";
UPDATE SONGS SET ARTIST = "Gretchen Wilson", TITLE = "All Jacked Up" WHERE LOCATION = "RP-0505";
UPDATE SONGS SET ARTIST = "Dixie Chicks", TITLE = "Goodbye Earl" WHERE LOCATION = "RP-0506";
UPDATE SONGS SET ARTIST = "Hank Williams Jr & Friends", TITLE = "That's How They Do It In Dixie" WHERE LOCATION = "RP-0507";
UPDATE SONGS SET ARTIST = "Big & Rich", TITLE = "Save A Horse (Ride A Cowboy)" WHERE LOCATION = "RP-0508";
UPDATE SONGS SET ARTIST = "Toby Keith", TITLE = "Get Drunk And Be Somebody" WHERE LOCATION = "RP-0509";
UPDATE SONGS SET ARTIST = "Toby Keith", TITLE = "As Good As I Once Was" WHERE LOCATION = "RP-0510";
UPDATE SONGS SET ARTIST = "Toby Keith & Willie Nelson", TITLE = "Beer For My Horses" WHERE LOCATION = "RP-0511";
UPDATE SONGS SET ARTIST = "Garth Brooks", TITLE = "Two Pina Coladas" WHERE LOCATION = "RP-0512";
UPDATE SONGS SET ARTIST = "Garth Brooks", TITLE = "Friends In Low Places" WHERE LOCATION = "RP-0513";
UPDATE SONGS SET ARTIST = "Bon Jovi & Jennifer Nettles", TITLE = "Who Says You Can't Go Home" WHERE LOCATION = "RP-0514";
UPDATE SONGS SET ARTIST = "Toby Keith", TITLE = "A Little Too Late" WHERE LOCATION = "RP-0515";
UPDATE SONGS SET ARTIST = "Shania Twain", TITLE = "That Don't Impress Me Much" WHERE LOCATION = "RP-0516";
UPDATE SONGS SET ARTIST = "Willie Nelson", TITLE = "On The Road Again" WHERE LOCATION = "RP-0519";

DELETE FROM SONGS WHERE LOCATION="RP-0339";