INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0691", "Kate Bush", "Hounds of Love");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0581", "Police", "Roxanne");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0582", "Calum Scott", "Dancing On My Own");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0583", "Lynn Anderson", "Rose Garden");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0584", "Connie Francis", "Stupid Cupid");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0585", "Queen", "We Are The Champions");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0586", "Kinks", "You Really Got Me");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0587", "Squeeze", "Up The Junction");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0588", "Drifters", "Under The Boardwalk");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0589", "Jackie Wilson", "Reet Petite");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0590", "Elkie Brooks", "Pearl's A Singer");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0591", "Elkie Brooks", "Don't Cry Out Loud");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0592", "Four Seasons", "December '63 (Oh What A Night)");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0593", "David Gray", "Babylon");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0594", "Fleetwood Mac", "Everywhere");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0595", "Macy Gray", "I Try");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0596", "Bruno Mars ", "24K Magic");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0597", "Lukas Graham", "7 Years");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0599", "Rita Ora", "Anywhere");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0601", "Ariana Grande & John Legend", "Beauty And The Beast");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0602", "LunchMoney Lewis", "Bills");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0605", "Sia", "Cheap Thrills");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0606", "OMI", "Cheerleader (Felix Jaehn Remix)");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0607", "The Chainsmokers ft. Halsey", "Closer");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0608", "Major Lazer ft. Justin Bieber & MO", "Cold Water");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0609", "Luis Fonsi & Daddy Yankee ft. Justin Bieber", "Despacito");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0610", "Portugal. The Man", "Feel It Still");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0611", "Psy", "Gangnam Style");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0613", "Carly Rae Jepsen ", "I Really Like You");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0615", "Ellie Goulding", "Love Me Like You Do");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0617", "Drake ft. Wizkid & Kyla", "One Dance");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0618", "Ariana Grande", "One Last Time");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0619", "LMFAO", "Party Rock Anthem");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0620", "Ed Sheeran", "Perfect");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0623", "Ed Sheeran", "Shape Of You");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0624", "Little Mix", "Shout Out To My Ex");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0625", "Walk The Moon", "Shut Up And Dance");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0626", "Justin Bieber", "Sorry");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0628", "Calvin Harris & Rihanna", "This Is What You Came For");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0630", "Shawn Mendes", "Treat You Better");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0632", "Silento", "Watch Me (Whip Nae Nae)");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0636", "Ariana Grande & Justin Bieber", "Stuck With U");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0637", "Ava Max", "Kings And Queens");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0638", "Billie Eilish", "Everything I Wanted");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0639", "Cardi B. ft. Megan Thee Stallion", "WAP");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0640", "Doja Cat", "Say So");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0641", "Dua Lipa", "Physical");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0642", "Ed Sheeran ft. Camila Cabello & Cardi B", "South Of The Border");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0643", "Eminem ft. Juice WRLD", "Godzilla");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0644", "Frozen 2", "Into The Unknown");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0645", "Halsey", "You Should Be Sad");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0647", "Jonas Brothers", "What A Man Gotta Do");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0648", "Justin Bieber ft. Quavo", "Intentions");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0649", "Lady Gaga & Ariana Grande", "Rain On Me");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0650", "Lewis Capaldi", "Before You Go");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0651", "Little Mix", "Holiday");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0652", "Roddy Ricch", "The Box");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0653", "Stormzy ft. Ed Sheeran & Burna Boy", "Own It");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0654", "Taylor Swift ft. Bon Iver", "Exile");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0655", "Tones & I", "Dance Monkey");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0656", "6ix9ine ft. Nicki Minaj", "Trollz");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0657", "Becky Hill ft. Shift K3Y", "Better Off Without You");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0658", "Billie Eilish", "No Time To Die");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0659", "Clean Bandit & Mabel ft. 24kGoldn", "Tick Tock");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0660", "Drake", "Toosie Slide");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0661", "Dua Lipa", "Don't Start Now");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0662", "Ellie Goulding", "River");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0663", "Future ft. Drake", "Life Is Good");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0664", "Great Big World & Christina Aguilera", "Fall On Me");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0666", "Jason Derulo", "Savage Love");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0667", "Justin Bieber", "Yummy");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0668", "Lady Gaga", "Stupid Love");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0669", "Lewis Capaldi", "Bruises");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0670", "Little Mix", "Break Up Song");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0671", "Megan Thee Stallion", "Savage");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0672", "SAINt JHN", "Roses (Imanbek Remix)");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0673", "Taylor Swift", "Cardigan");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0674", "The Weeknd", "Blinding Light");
INSERT INTO SONGS (LOCATION, ARTIST, TITLE)
VALUES ("GP-0675", "Topic ft. A7S", "Breaking Me");