#
# Local development overrides for Docker Compose.
#
# Purpose: Layer on top of docker-compose.yml for local dev.
#
# Changes made:
# - Build images from local sources for backend and frontend
# - Expose high dev ports via Caddy dev config (see Caddyfile.dev)
# - Provide default dev env vars and autorestart behavior suitable for dev
# - Add optional platform override for Apple Silicon
#
# @LLM_USAGE Fully LLM generated.

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      # Uncomment to force local platform build (e.g., Apple Silicon)
      # platforms:
      #   - linux/arm64
    image: jocks-karaoke/backend:local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Nak4pic.mysql}
      JWT_SECRET: ${JWT_SECRET:-dev}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jocks-karaoke
    ports:
      - "9090:9090"

  frontend:
    build:
      context: ../frontend
      args:
        REACT_APP_BACKEND_URL: /api
      # Uncomment to force local platform build (e.g., Apple Silicon)
      # platforms:
      #   - linux/arm64
    image: jocks-karaoke/frontend:local
    restart: unless-stopped
    expose:
      - "3000"

  caddy:
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"


